"""Phylogenetic tree generation via Yule-with-sampling on SSWM dynamics."""

from dataclasses import dataclass, field

import numpy as np

from trellis.cache import FitnessCache
from trellis.fitness import compute_fitness_aa
from trellis.fold_enum import ConformationDatabase
from trellis.genetic_code import translate
from trellis.ligand import Ligand
from trellis.sswm import compute_sswm_probabilities


@dataclass
class PhylogenyNode:
    """A node in the phylogenetic tree."""

    id: int
    dna: str
    aa: str
    fitness: float
    depth: int
    is_tip: bool
    parent_id: int | None


@dataclass
class Phylogeny:
    """A phylogenetic tree generated by Yule-with-sampling on SSWM dynamics."""

    nodes: list[PhylogenyNode]
    root_id: int
    metadata: dict = field(default_factory=dict)


def generate_phylogeny(
    start_dna: str,
    ligand: Ligand,
    mj_matrix: np.ndarray,
    db: ConformationDatabase,
    n_steps: int = 100,
    Ne: float = 50.0,
    beta: float = 0.80,
    psi: float = 0.05,
    temperature: float = 1.0,
    min_active_lineages: int = 1,
    max_active_lineages: int = 70,
    max_total_nodes: int = 100000,
    rng: np.random.Generator | None = None,
    fitness_cache: FitnessCache | None = None,
) -> Phylogeny:
    """Generate a phylogenetic tree via Yule-with-sampling on SSWM dynamics."""
    if rng is None:
        rng = np.random.default_rng()
    if fitness_cache is None:
        fitness_cache = FitnessCache()

    root_aa = translate(start_dna)
    if root_aa not in fitness_cache:
        r = compute_fitness_aa(root_aa, ligand, mj_matrix, temperature, db=db)
        fitness_cache.put(root_aa, r)
    root_fitness = fitness_cache.get(root_aa).fitness

    root = PhylogenyNode(
        id=0, dna=start_dna, aa=root_aa,
        fitness=root_fitness, depth=0,
        is_tip=False, parent_id=None,
    )
    nodes = [root]
    active = [0]

    for depth in range(1, n_steps + 1):
        if not active:
            break
        if len(nodes) >= max_total_nodes:
            for node_id in active:
                nodes[node_id].is_tip = True
            break

        new_active = []
        # Determine which lineages get sampled (become tips) this step.
        # Shuffle so the min_active_lineages protection isn't biased by order.
        order = rng.permutation(len(active)).tolist()
        sampled = set()
        for i in order:
            if rng.random() < psi:
                if len(active) - len(sampled) > min_active_lineages:
                    sampled.add(i)

        for idx, parent_id in enumerate(active):
            parent = nodes[parent_id]

            if idx in sampled:
                parent.is_tip = True
                continue

            n_daughters = 2 if rng.random() < beta else 1

            mutant_dnas, probs = compute_sswm_probabilities(
                parent.dna, parent.fitness, ligand, mj_matrix,
                Ne, temperature, fitness_cache, db,
            )

            if probs.sum() == 0:
                parent.is_tip = True
                continue

            for _ in range(n_daughters):
                idx = rng.choice(len(mutant_dnas), p=probs)
                child_dna = mutant_dnas[idx]
                child_aa = translate(child_dna)
                child_fitness = fitness_cache.get(child_aa).fitness

                child = PhylogenyNode(
                    id=len(nodes), dna=child_dna, aa=child_aa,
                    fitness=child_fitness, depth=depth,
                    is_tip=False, parent_id=parent_id,
                )
                nodes.append(child)
                new_active.append(child.id)

        if len(new_active) > max_active_lineages:
            n_to_remove = len(new_active) - max_active_lineages
            remove_indices = set(
                rng.choice(len(new_active), size=n_to_remove, replace=False).tolist()
            )
            for idx in remove_indices:
                nodes[new_active[idx]].is_tip = True
            new_active = [
                new_active[i] for i in range(len(new_active))
                if i not in remove_indices
            ]

        active = new_active

    for node_id in active:
        nodes[node_id].is_tip = True

    metadata = {
        "n_steps": n_steps,
        "Ne": Ne,
        "beta": beta,
        "psi": psi,
        "min_active_lineages": min_active_lineages,
        "temperature": temperature,
        "ligand_sequence": ligand.sequence,
        "ligand_positions": list(ligand.positions),
        "n_nodes": len(nodes),
        "n_tips": sum(1 for n in nodes if n.is_tip),
    }

    return Phylogeny(nodes=nodes, root_id=0, metadata=metadata)
